DROP DATABASE IF EXISTS myWebsite;
CREATE DATABASE myWebsite;
USE myWebsite;

CREATE TABLE blog(
    id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '글 번호',
	title VARCHAR(300) NOT NULL COMMENT '제목',
	`body` TEXT NOT NULL COMMENT '내용',
	writer_id INT(10) UNSIGNED NOT NULL COMMENT '작성자',
	hit_cnt SMALLINT(10) NOT NULL DEFAULT '0' COMMENT '조회수',
	reg_date DATETIME NOT NULL DEFAULT NOW() COMMENT '작성일자',
	update_date DATETIME NOT NULL DEFAULT NOW() COMMENT '수정일자'
);
